/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ApiDictionaryRouteImport } from './routes/api/dictionary'
import { Route as ApiGutenbergRouteImport } from './routes/api/gutenberg'
import { Route as ApiGutendexSplatRouteImport } from './routes/api/gutendex.$'
import { Route as ApiOpenlibrarySplatRouteImport } from './routes/api/openlibrary.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDictionaryRoute = ApiDictionaryRouteImport.update({
  id: '/api/dictionary',
  path: '/api/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGutenbergRoute = ApiGutenbergRouteImport.update({
  id: '/api/gutenberg',
  path: '/api/gutenberg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGutendexSplatRoute = ApiGutendexSplatRouteImport.update({
  id: '/api/gutendex/$',
  path: '/api/gutendex/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenlibrarySplatRoute = ApiOpenlibrarySplatRouteImport.update({
  id: '/api/openlibrary/$',
  path: '/api/openlibrary/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/api/dictionary': typeof ApiDictionaryRoute
  '/api/gutenberg': typeof ApiGutenbergRoute
  '/api/gutendex/$': typeof ApiGutendexSplatRoute
  '/api/openlibrary/$': typeof ApiOpenlibrarySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/api/dictionary': typeof ApiDictionaryRoute
  '/api/gutenberg': typeof ApiGutenbergRoute
  '/api/gutendex/$': typeof ApiGutendexSplatRoute
  '/api/openlibrary/$': typeof ApiOpenlibrarySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/api/dictionary': typeof ApiDictionaryRoute
  '/api/gutenberg': typeof ApiGutenbergRoute
  '/api/gutendex/$': typeof ApiGutendexSplatRoute
  '/api/openlibrary/$': typeof ApiOpenlibrarySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/thank-you'
    | '/api/dictionary'
    | '/api/gutenberg'
    | '/api/gutendex/$'
    | '/api/openlibrary/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/thank-you'
    | '/api/dictionary'
    | '/api/gutenberg'
    | '/api/gutendex/$'
    | '/api/openlibrary/$'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/thank-you'
    | '/api/dictionary'
    | '/api/gutenberg'
    | '/api/gutendex/$'
    | '/api/openlibrary/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiDictionaryRoute: typeof ApiDictionaryRoute
  ApiGutenbergRoute: typeof ApiGutenbergRoute
  ApiGutendexSplatRoute: typeof ApiGutendexSplatRoute
  ApiOpenlibrarySplatRoute: typeof ApiOpenlibrarySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dictionary': {
      id: '/api/dictionary'
      path: '/api/dictionary'
      fullPath: '/api/dictionary'
      preLoaderRoute: typeof ApiDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gutenberg': {
      id: '/api/gutenberg'
      path: '/api/gutenberg'
      fullPath: '/api/gutenberg'
      preLoaderRoute: typeof ApiGutenbergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gutendex/$': {
      id: '/api/gutendex/$'
      path: '/api/gutendex/$'
      fullPath: '/api/gutendex/$'
      preLoaderRoute: typeof ApiGutendexSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openlibrary/$': {
      id: '/api/openlibrary/$'
      path: '/api/openlibrary/$'
      fullPath: '/api/openlibrary/$'
      preLoaderRoute: typeof ApiOpenlibrarySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ThankYouRoute: ThankYouRoute,
  ApiDictionaryRoute: ApiDictionaryRoute,
  ApiGutenbergRoute: ApiGutenbergRoute,
  ApiGutendexSplatRoute: ApiGutendexSplatRoute,
  ApiOpenlibrarySplatRoute: ApiOpenlibrarySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
